
import { Header } from './components/header/header.component';
import { HeaderBlank } from './components/header/header-blank.component';

// import logo from './logo.svg';
// import './App.css';

function App() {
  return (
    <>
      <Header/>
      <HeaderBlank/>
      <div className="body container">
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        <p>hello</p>
        <p>hi</p>
        <p>bye</p>
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
        hello
        hi
        good
      </div>
    </>
  );
}

export default App;
